"""Phase 4 + 5 + 6 driver: run QC, build leakage-safe splits, write the manifest
and the two markdown reports.

    python scripts/cricket/build_splits.py
    python scripts/cricket/build_splits.py --min-videos-for-ratio 10
    python scripts/cricket/build_splits.py --out-report evaluation/dataset_quality_report.md

Writes:
  data/cricket_understanding/splits/{train,val,test}.txt
  data/cricket_understanding/splits/split_meta.json
  data/cricket_understanding/dataset_manifest.json
  evaluation/dataset_quality_report.md
"""
from __future__ import annotations

import argparse
import os
import sys
from collections import Counter, defaultdict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from src.cricket_understanding import manifest as manifest_mod   # noqa: E402
from src.cricket_understanding import qc, registry, schema, splits as splits_mod  # noqa: E402

REPORT = os.path.join("evaluation", "dataset_quality_report.md")


def _n_frames_by_id(records):
    return {r.video_id: r.frame_count for r in records if r.frame_count}


def build_report(qc_result, split_result, manifest, n_annotated_videos,
                 n_annotated_deliveries, records) -> str:
    lines = []
    A = lines.append
    A("# Dataset Quality Report -- cricket_understanding_v1")
    A("")
    A("Generated by `scripts/cricket/build_splits.py`. Every number below is "
      "computed from files on disk.")
    A("")
    A("> **Nothing in this report was auto-repaired.** QC reports; it never "
      "rewrites a human annotation.")
    A("")

    A("## 1. Corpus")
    A("")
    A("| Metric | Value |")
    A("|---|---|")
    A(f"| Registered videos (real files) | {len(records)} |")
    A(f"| Un-probeable (recorded, not dropped) | "
      f"{sum(1 for r in records if r.probe_status != 'OK')} |")
    A(f"| Videos with ANY human annotation | {n_annotated_videos} |")
    A(f"| Videos passing QC with no ERROR | "
      f"{qc_result['n_videos'] - sum(1 for v in qc_result['per_video'] if any(i['severity'] == 'ERROR' for i in v.get('issues', [])))} |")
    A(f"| Human-annotated deliveries | {n_annotated_deliveries} |")
    A(f"| Person-role annotations | {manifest['person_role_annotations']} |")
    A(f"| Bowling-phase annotations | {manifest['bowling_phase_annotations']} |")
    A("")

    A("## 2. Split (VIDEO level -- never frame level)")
    A("")
    A("| Split | Videos | Actual share | Target share |")
    A("|---|---|---|---|")
    tot = sum(len(v) for v in split_result.splits.values()) or 1
    for name in ("train", "val", "test"):
        n = len(split_result.splits.get(name, []))
        A(f"| {name} | {n} | {n / tot:.1%} | "
          f"{split_result.target.get(name, 0):.0%} |")
    A("")
    A(f"- Strategy: `{split_result.strategy}`")
    A(f"- Groups: {split_result.n_groups} (group key = "
      f"`bowler:<id>` when known, else `view:<camera prefix>`)")
    A(f"- Ratio split applied: **{split_result.ratio_split_applied}**")
    A(f"- Grouping degraded: **{split_result.grouping_degraded}**")
    if split_result.note:
        A(f"- **NOTE:** {split_result.note}")
    if split_result.residual_leakage_risk:
        A("")
        A(f"> **WARNING** {split_result.residual_leakage_risk}")
    A("")
    A("The grouping key never *reduces* caution: when bowler ids are unknown the "
      "camera-view prefix is used, which can only merge more aggressively, never "
      "less. Set `--bowler-id` at registration time once bowlers are identified "
      "and the split will group by bowler automatically.")
    A("")

    A("## 3. Leakage checks")
    A("")
    leaks = [i for i in qc_result["issues"] if i["code"] == "SPLIT_LEAKAGE"]
    A(f"- Video appears in >1 split: **{len(leaks)}**")
    A(f"- Duplicate video_ids in the registry: "
      f"**{qc_result['issues_by_code'].get('DUPLICATE_VIDEO_ID', 0)}**")
    A("")
    if not leaks:
        A("Result: **PASS** -- no video is in more than one split.")
    else:
        A("Result: **FAIL** -- see the issue list below.")
    A("")

    A("## 4. Annotation issues by code")
    A("")
    if not qc_result["issues"]:
        A("No issues found.")
    else:
        A("| Code | Count |")
        A("|---|---|")
        for code, n in sorted(qc_result["issues_by_code"].items()):
            A(f"| `{code}` | {n} |")
    A("")

    A("## 5. Issues by severity")
    A("")
    A("| Severity | Count | Meaning |")
    A("|---|---|---|")
    sev_meaning = {
        "ERROR": "blocks the clip from train/val/test until a human fixes it",
        "WARNING": "suspicious but usable; a human should look",
        "INFO": "informational (gaps, uncertain frames, unknown camera view)",
    }
    for sev in ("ERROR", "WARNING", "INFO"):
        A(f"| {sev} | {qc_result['issues_by_severity'].get(sev, 0)} | "
          f"{sev_meaning[sev]} |")
    A("")

    errs = [i for i in qc_result["issues"] if i["severity"] == "ERROR"]
    A("## 6. Every ERROR (must be resolved by a human)")
    A("")
    if not errs:
        A("None.")
    else:
        A("| Code | Video | Frame | Track | Delivery | Message |")
        A("|---|---|---|---|---|---|")
        for i in errs[:200]:
            A(f"| `{i['code']}` | `{i['video_id']}` | {i.get('frame_id', '-')} | "
              f"{i.get('track_id', '-')} | {i.get('delivery_id') or '-'} | "
              f"{i['message']} |")
        if len(errs) > 200:
            A(f"| ... | | | | | {len(errs) - 200} more |")
    A("")

    A("## 7. Checks implemented")
    A("")
    A("| Check | Code |")
    A("|---|---|")
    for code, doc in (
        ("DUPLICATE_VIDEO_ID", "duplicate video IDs"),
        ("MISSING_ANNOTATED_FRAMES", "missing frames inside a track's range"),
        ("INVALID_FRAME_NUMBER", "invalid frame numbers"),
        ("IMPOSSIBLE_BBOX", "impossible bounding boxes"),
        ("MISSING_ANNOTATOR_ID", "missing annotator ID"),
        ("CONFLICTING_ROLE", "overlapping / conflicting labels"),
        ("OVERLAPPING_BBOX", "boxes of two tracks overlap"),
        ("RELEASE_OUTSIDE_DELIVERY", "release frame outside the delivery window"),
        ("PHASE_ORDER_VIOLATION", "phase ordering errors"),
        ("MISSING_BOWLER_TRACK", "missing bowler track"),
        ("IMPOSSIBLE_PHASE_SEQUENCE", "delivery with impossible phase sequence"),
        ("DUPLICATE_DELIVERY_ID", "duplicate delivery IDs"),
        ("FRAME_OUT_OF_VIDEO_RANGE", "frame index beyond the video length"),
        ("SPLIT_LEAKAGE", "a video in more than one split"),
        ("DUPLICATE_ANNOTATION", "duplicate (frame, track) rows"),
        ("UNCERTAIN_FRAMES", "annotator-flagged uncertain frames (kept, flagged)"),
        ("SCENE_IMPOSSIBLE_BOX", "impossible scene geometry"),
    ):
        A(f"| {doc} | `{code}` |")
    A("")
    A("Valid phase ordering enforced:")
    A("")
    A("```")
    A(" <= ".join(schema.ORDERED_PHASE_SEQUENCE))
    A("```")
    A("")
    A("## 8. Training readiness")
    A("")
    ready = manifest["n_videos_trainable"]
    A(f"- Videos usable for train/val/test right now: **{ready}**")
    if ready == 0:
        A("")
        A("**NOT READY.** No clip has human labels yet. The first milestone "
          "(`VIDEO -> HUMAN-LABELED DATASET -> VALID DATASET -> BASELINE -> "
          "TRAINING -> HELD-OUT TEST`) has not been reached. No accuracy figure "
          "can honestly be produced at this point.")
    else:
        A("")
        A("Proceed to Phase 7 generation. Metrics are still meaningless until a "
          "held-out test set exists (Phase 10-11).")
    A("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--registry", default=registry.VIDEOS_JSONL)
    ap.add_argument("--out-report", default=os.path.join(
        os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), REPORT))
    ap.add_argument("--seed", type=int, default=splits_mod.RANDOM_STATE)
    ap.add_argument("--min-videos-for-ratio", type=int,
                    default=splits_mod.MIN_VIDEOS_FOR_RATIO_SPLIT)
    ap.add_argument("--no-bowler-grouping", action="store_true",
                    help="disable bowler grouping (NOT recommended)")
    args = ap.parse_args(argv)

    splits_mod.MIN_VIDEOS_FOR_RATIO_SPLIT = args.min_videos_for_ratio
    schema.ensure_dirs()
    records = registry.load_records(args.registry)
    if not records:
        print("No videos registered. Run scripts/cricket/register_videos.py first.",
              file=sys.stderr)
        return 2

    n_frames = _n_frames_by_id(records)
    probe = qc.run_all(video_ids=[r.video_id for r in records],
                       n_frames_by_id=n_frames, records=records)
    print(f"QC pass 1: {probe['n_issues']} issue(s) over {probe['n_videos']} video(s)")

    split_result = splits_mod.make_splits(records, seed=args.seed,
                                          group_by_bowler=not args.no_bowler_grouping)
    split_issues = splits_mod.verify(split_result)
    if split_issues:
        print("FATAL: split produced leakage:",
              [i.line() for i in split_issues], file=sys.stderr)
        return 3
    splits_mod.save_splits(split_result)
    print(f"Split: {split_result.strategy} -> " +
          ", ".join(f"{k}={len(v)}" for k, v in split_result.splits.items()))

    qc_result = qc.run_all(video_ids=[r.video_id for r in records],
                           n_frames_by_id=n_frames,
                           splits=split_result.splits, records=records)
    print(f"QC pass 2: {qc_result['n_issues']} issue(s)")

    mf = manifest_mod.build(records=records, qc_result=qc_result,
                            splits=split_result.splits)
    manifest_mod.save(mf)
    print(f"Manifest: {mf['n_videos_registered']} videos, "
          f"{mf['n_videos_annotated']} annotated, "
          f"{mf['n_videos_trainable']} trainable, "
          f"{mf['deliveries_annotated']} deliveries")

    n_ann_del = sum(len(schema.load_deliveries(r.video_id)) for r in records)
    report = build_report(qc_result, split_result, mf,
                          mf["n_videos_annotated"], n_ann_del, records)
    os.makedirs(os.path.dirname(os.path.abspath(args.out_report)), exist_ok=True)
    with open(args.out_report, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(report)
    print(f"Report: {args.out_report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
